In [1]:
import nltk
import pandas as pd
from nltk.corpus import stopwords
import pandas as pd
import numpy as np
from nltk import sent_tokenize, word_tokenize
from nltk.tokenize import TweetTokenizer
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer 

In [2]:
# tweets = pd.read_csv("C:\\Users\\ATIF SHAIK\\OneDrive\\Documents\\train.csv")

In [3]:
tweet = pd.read_csv("C:\\Users\\ATIF SHAIK\\OneDrive\\Documents\\Tweets.csv") 

In [4]:
tweet.head()

textID                                               text  \
0  cb774db0d1                I`d have responded, if I were going   
1  549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2  088c60f138                          my boss is bullying me...   
3  9642c003ef                     what interview! leave me alone   
4  358bd9e861   Sons of ****, why couldn`t they put them on t...   

                         selected_text sentiment  
0  I`d have responded, if I were going   neutral  
1                             Sooo SAD  negative  
2                          bullying me  negative  
3                       leave me alone  negative  
4                        Sons of ****,  negative

In [5]:
tweet.drop(tweet.index[tweet['sentiment'] == 'neutral'], inplace = True)

In [6]:
tweet['sentiment'].value_counts()

positive    8582
negative    7781
Name: sentiment, dtype: int64

In [7]:
tweet 

textID                                               text  \
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
6      6e0c6d75b1  2am feedings for the baby are fun when he is a...   
...           ...                                                ...   
27475  b78ec00df5                                     enjoy ur night   
27476  4eac33d1c0   wish we could come see u on Denver  husband l...   
27477  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27478  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27479  ed167662a5                         But it was worth it  ****.   

                    selected_text sentiment  
1                        Sooo SAD  negative  
2                     bullying me  negative  
3                  leave me alone  negative  
4                   Sons of ****,  negative  
6                             fun  positive  
...                           ...       ...  
27475                       enjoy  positive  
27476                      d lost  negative  
27477               , don`t force  negative  
27478   Yay good for both of you.  positive  
27479  But it was worth it  ****.  positive  

[16363 rows x 4 columns]

In [8]:
# tweet['label'].value_counts()

In [9]:
tweet.isnull().sum()

textID           0
text             0
selected_text    0
sentiment        0
dtype: int64

In [10]:
tweet.duplicated().sum()

0

In [11]:
print(tweet.iloc[0].text)
print(tweet.iloc[1].text)

 Sooo SAD I will miss you here in San Diego!!!
my boss is bullying me...


In [12]:
import string
punct = string.punctuation
punct = list(punct)
stops = stopwords.words('english')
tokenizer = TweetTokenizer()

In [13]:
punch = []
st = []
def clean(n):
    n = tokenizer.tokenize(n)
    for i in n:
        if i in punct:
            punch.append(i)
            n.remove(i)
    for j in n:
        if j in stops:
            st.append(j)
            n.remove(j)
            
    return n

In [14]:
tweet['text'] = tweet['text'].apply(clean)

In [15]:
lemmatizer = WordNetLemmatizer()
ps = PorterStemmer()

In [16]:
def lem(a):
    for i,j in enumerate(a):
        a[i] = lemmatizer.lemmatize(j, pos='a')
        
    return a
        
tweet['text'] = tweet['text'].apply(lem)

In [17]:
tweet.head(8)

textID                                               text  \
1   549e992a42          [Sooo, SAD, I, miss, here, San, Diego, !]   
2   088c60f138                              [boss, bullying, ...]   
3   9642c003ef                          [interview, leave, alone]   
4   358bd9e861  [Sons, *, ,, couldn, they, put, on, releases, ...   
6   6e0c6d75b1  [2am, feedings, the, baby, fun, he, all, smile...   
9   fc2cbefa9d  [Journey, ?, Wow, ..., u, became, cool, hehe, ...   
11  16fab9f95b  [I, really, really, like, song, Love, Story, T...   
12  74a76f6e0a      [My, Sharpie, running, DANGERously, low, ink]   

                   selected_text sentiment  
1                       Sooo SAD  negative  
2                    bullying me  negative  
3                 leave me alone  negative  
4                  Sons of ****,  negative  
6                            fun  positive  
9   Wow... u just became cooler.  positive  
11                          like  positive  
12                   DANGERously  negative

In [18]:
def stem(n):
    for i,j in enumerate(n):
        n[i] = ps.stem(j)
        
    return n
tweet['text'] = tweet['text'].apply(stem)

In [19]:
def lower(n):
    for i in n:
        i = i.lower()
    return n
tweet['text'] = tweet['text'].apply(lower)

In [20]:
def join(n):
    return ' '.join(n)
tweet['text'] = tweet['text'].apply(join)

In [21]:
tweet.head(8)

textID                                               text  \
1   549e992a42                   sooo sad i miss here san diego !   
2   088c60f138                                     boss bulli ...   
3   9642c003ef                                interview leav alon   
4   358bd9e861   son * , couldn they put on releas alreadi bought   
6   6e0c6d75b1             2am feed the babi fun he all smile coo   
9   fc2cbefa9d  journey ? wow ... u becam cool hehe ... that p...   
11  16fab9f95b  i realli realli like song love stori taylor swift   
12  74a76f6e0a                       my sharpi run danger low ink   

                   selected_text sentiment  
1                       Sooo SAD  negative  
2                    bullying me  negative  
3                 leave me alone  negative  
4                  Sons of ****,  negative  
6                            fun  positive  
9   Wow... u just became cooler.  positive  
11                          like  positive  
12                   DANGERously  negative

In [22]:
def senti(n):
    if n=='positive':
        return 1
    elif n=='negative':
        return 0
tweet['Senti'] = tweet['sentiment'].apply(senti)

In [23]:
tweet.head(9)

textID                                               text  \
1   549e992a42                   sooo sad i miss here san diego !   
2   088c60f138                                     boss bulli ...   
3   9642c003ef                                interview leav alon   
4   358bd9e861   son * , couldn they put on releas alreadi bought   
6   6e0c6d75b1             2am feed the babi fun he all smile coo   
9   fc2cbefa9d  journey ? wow ... u becam cool hehe ... that p...   
11  16fab9f95b  i realli realli like song love stori taylor swift   
12  74a76f6e0a                       my sharpi run danger low ink   
13  04dd1d2e34                  want go music tonight i lost voic   

                   selected_text sentiment  Senti  
1                       Sooo SAD  negative      0  
2                    bullying me  negative      0  
3                 leave me alone  negative      0  
4                  Sons of ****,  negative      0  
6                            fun  positive      1  
9   Wow... u just became cooler.  positive      1  
11                          like  positive      1  
12                   DANGERously  negative      0  
13                          lost  negative      0

In [24]:
X = tweet['text']
y = tweet['Senti']

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tf = TfidfVectorizer(max_features=3000)
cv = CountVectorizer(max_features=5000)

In [26]:
X = tf.fit_transform(X)
X = X.toarray() 

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
tree = RandomForestClassifier(n_estimators=200)
vector = SVC(kernel = 'linear')
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
gauss = GaussianNB()
reg = LogisticRegression()

In [28]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01) 

In [30]:
# gauss = () 

In [31]:
clf.fit(X_train, y_train) 
clf.score(X_test, y_test) 

0.8902439024390244

In [32]:
# vector.fit(X_train, y_train) 
# vector.score(X_test, y_test) 

In [33]:
# tree.fit(X_train, y_train) 
# tree.score(X_test, y_test) 

In [143]:
text = "The girl in the hair salon asked me 'Shall I trim your eyebrows!' How old do I feel?" 

In [144]:
'''Positive
i don't know why my dad always comments on how much i'm eating because it makes me want to die
i'm tired of losing friends and people close to me cause of being suicidal
i want to kill my self
i'm in pain, wanna put ten shots in my brain i've been tripped by some things i can't change suicidal
Negative
in the uk the biggest killer for men is suicide. Good job
feminists ignoring their issues a dear friend of mine committed suicide with a shotgun two years ago i don't say this lightly - hemingway's life ended by suicide. His life was actually a loss
these r not ur problems dear!! these rur x bf's commitng suicide

'''

"Positive\ni don't know why my dad always comments on how much i'm eating because it makes me want to die\ni'm tired of losing friends and people close to me cause of being suicidal\ni want to kill my self\ni'm in pain, wanna put ten shots in my brain i've been tripped by some things i can't change suicidal\nNegative\nin the uk the biggest killer for men is suicide. Good job\nfeminists ignoring their issues a dear friend of mine committed suicide with a shotgun two years ago i don't say this lightly - hemingway's life ended by suicide. His life was actually a loss\nthese r not ur problems dear!! these rur x bf's commitng suicide\n\n"

In [145]:
random = []
random2 = []
# clean(word):
n = tokenizer.tokenize(text)
for i in n:
    if i in punct:
#         random.append(i)
        n.remove(i)
    else:
        pass
for j in n:
    if j in stops:
#         random.append(j)
        n.remove(j)
    else:
        pass           
# lemmatizing
for i,j in enumerate(n):
    n[i] = lemmatizer.lemmatize(j, pos='a')
    
for i,j in enumerate(n):
    n[i] = ps.stem(j)
    
for i in n:
        i = i.lower()
    
final = ' '.join(n)
final = [final]
final = tf.transform(final).toarray() 
ans = clf.predict(final)  
l = [0.48, 0.49, 0.50, 0.51, 0.52, 0.53] 
prob = clf.predict_proba(final)
prob = prob[0][1]
f = "{0:.2f}" 
prob = f.format(prob) 
prob = float(prob)

if prob in l: 
    print('Neutral Tweet') 
elif ans == 1:
    print('Positive Tweet')
elif ans == 0:
    print('Negative Tweet')
    

iam prob 0.4
[[0.59612507 0.40387493]]
Negative Tweet


In [37]:
# import pickle
# # with open('Tweets.pkl', 'wb') as file:
# #     pickle.dump(clf, file)
# with open('TweetsTf.pkl', 'wb') as fille:
#     pickle.dump(tf, fille)
    

In [72]:
clf.predict(X_test[:5])

array([1, 1, 1, 1, 0], dtype=int64)

In [88]:

# for i in clf.predict_proba(X_test[:5]):
#     k = i[1]
#     f = "{0:.2f}"
#     k = f.format(k)
#     print(k)

0.84
0.96
0.95
0.76
0.44


In [89]:
clf.predict_proba(X_test[:5])

array([[0.15554483, 0.84445517],
       [0.03524712, 0.96475288],
       [0.05418959, 0.94581041],
       [0.24131055, 0.75868945],
       [0.55698669, 0.44301331]])